### ISSUE TITLE
CINII検索の検索結果一覧画面のページネーションが使いにくい

### ISSUE THREAD

**Issue by t-matsumo** [yaaaaashiki/Escapism#178]
数字がいっぱい表示されてるだけでなんか違う

![image](https://user-images.githubusercontent.com/23055451/30241688-5c2b1116-95c3-11e7-96e9-66e24818fd3d.png)

**Comment by t-matsumo** [comment]
↓commit:"CiNii+検索"とcommit:"検索"でどう違うの？？
![image](https://user-images.githubusercontent.com/23055451/30274618-32d005ca-9739-11e7-92c4-082c2b1186cc.png)

**Comment by t-matsumo** [comment]
まさかの負の遺産？？？

**Comment by yaaaaashiki** [comment]
推薦画面からのクエリと、ciniis からのクエリが違うから辻褄合わせたところ〜ｗ

ページネーションもモデルと紐付いてないから gem 使えなくて自作してる

**Comment by yaaaaashiki** [comment]
> まさかの負の遺産？？？

exactly!

**Comment by t-matsumo** [comment]
kaminariは配列も使えるけど...
これ消しても影響ないよね～

**Comment by yaaaaashiki** [comment]
行けるなら是非ｂ

**Comment by yaaaaashiki** [comment]
merged
