### ISSUE TITLE
研究室ごとのチャット機能

### ISSUE THREAD

**Issue by yaaaaashiki** [yaaaaashiki/Escapism#184]
### ユーザの role 定義
user テーブルに role を追加
```
role = 1 (研究生)
role = 2 (生徒)

today.year - user.year >= 3 ? 研究室 : 生徒 
```

### URI
各研究室は 1 つのチャットページを持つ 
```
labos/:lab_id/chatrooms
```

`:lab_id` が `1〜8` 以外の場合、`404`を返す 

 ### チャット権限
`role = 1` のユーザは、所属している研究室チャットにのみ**閲覧、書き込み可能**
その他の研究室チャットは**閲覧可能、書き込み不可**

`role = 2` のユーザは全ての研究室チャットを**閲覧、書き込み可能**

### メッセージテーブル
```
id         :integer          not null, primary key
body       :text(65535)
user_id    :integer
labo_id    :integer
timestamp
```

 ### チャット表示内容
```
ユーザネーム、role、メッセージ、書き込み日時
```

**Comment by t-matsumo** [comment]
> d.year - user.year >= 3 ? 研究室 : 生徒 
留年生は？？
修正難しそうwww

**Comment by yaaaaashiki** [comment]
それ考えたけど不可能じゃない？

アプリ上で何留してるか入力させれば取れるけど、、w

**Comment by yaaaaashiki** [comment]
編集権限渡すことになるのか...

研究室ごとにパスワードとか作るとか？

**Comment by t-matsumo** [comment]
そうするか、管理者（誰だよ）が頑張る

**Comment by yaaaaashiki** [comment]
管理者 (@t-matsumoto) が頑張り制御する

**Comment by yaaaaashiki** [comment]
merged
