### ISSUE TITLE
DBにViewを作成（検討）

### ISSUE THREAD

**Issue by t-matsumo** [yaaaaashiki/Escapism#217]
理由:
1.データ取得の際,一部コントローラにSQLを直書きしているためソースが読みにくい
2.マテリアライズド・ビューが使えるとビューの更新が必要だがキャッシュを利用して高速にデータを取得できる（特に変化しないデータに有効）

検討事項:
1.そもそもここまでやる必要があるのかが謎（勉強するという意味ではあり）
2.mysqlだとマテリアライズド・ビューが実装されていないためpostgresqlなどに変更する必要あり

参考サイト:
http://319ring.net/blog/archives/2892/

**Comment by t-matsumo** [comment]
マテリアライズド・ビューは、MYSQLでやるならトリガを使うなどして自作すればOK

**Comment by yaaaaashiki** [comment]
> 1.データ取得の際,一部コントローラにSQLを直書きしているためソースが読みにくい

N + 1 問題を考えると、SQL 直書きは仕方ないはず。
SQL のリファクタリングではダメ？
または多対多のテーブルを作るか。でもそれをすると変更範囲が多くなる...

**Comment by t-matsumo** [comment]
読みにくいっていうのは、rubyのコードの中にSQLがあると余計な情報があって嫌だなーっていう意味だから、みんなが気にならなければOK

**Comment by t-matsumo** [comment]
やらなそうなためクローズ
