### ISSUE TITLE
adminページのoffilineっている？？

### ISSUE THREAD

**Issue by t-matsumo** [yaaaaashiki/Escapism#241]

**Comment by yaaaaashiki** [comment]
AdminLTE のテンプレートなんだよねえｗ

以下参考
[Page template](https://adminlte.io/themes/AdminLTE/index2.html)
[Github](https://github.com/nicolas-besnard/adminlte2-rails)

**Comment by yaaaaashiki** [comment]
消しますかｗ

**Comment by yaaaaashiki** [comment]
merged
