### ISSUE TITLE
adminユーザの登録方法

### ISSUE THREAD

**Issue by t-matsumo** [yaaaaashiki/Escapism#247]

**Comment by t-matsumo** [comment]
adminユーザのアカウントは普通のユーザのやつと一緒でいいよね？？

普通のログインのときと同じメールアドレスとパスワードでadminページにログインするイメージ

**Comment by yaaaaashiki** [comment]
あれ、この issue って「admin ユーザの登録方法の追加」だと思ってた〜

dev 環境だと
```ruby
AdminUser.seed(
  { id: 1,
    username: 'admin1',
    password_digest: BCrypt::Password.create('password')
  }
)
```
のみだからその修正・改善みたいな

**Comment by yaaaaashiki** [comment]
> 普通のログインのときと同じメールアドレスとパスワードでadminページにログインするイメージ

`app/controllers/admin/sessions_controller.rb`
とは別に作るってこと〜？
二つはいらないんじゃないかな....

**Comment by t-matsumo** [comment]
sorceryの仕様によるけど、admin権限ありユーザのテーブルを作って、そのテーブルて普通のユーザアカウントの主キー持ってれば新しくadmin関係の処理書かなくていいから楽かなーって思ったけど難しいかな？？

普通のユーザ用とadmin用のパスワード覚えるのがめんどくさいって理由もあるwww

**Comment by yaaaaashiki** [comment]
そういうことか〜
セキュリティ的に、1 つのログイン情報でサービスと admin に入れるのはよくないと思うな〜
