### ISSUE TITLE
開発の終わったブランチのマージ

### ISSUE THREAD

**Issue by t-matsumo** [yaaaaashiki/Escapism#259]

**Comment by yaaaaashiki** [comment]
[Feature/modify signup](https://github.com/yaaaaashiki/Escapism/pull/226) ブランチのこと？
テストが通ったらマージしようと思っているよ〜

**Comment by t-matsumo** [comment]
それ以外の乱立してるやつ（2つくらいだけど）は[WIP]？？

**Comment by yaaaaashiki** [comment]
WIP つけておきました〜
@t-matsumo のやつは、後ほどレビューします〜ｂ

**Comment by yaaaaashiki** [comment]
Thanks!
