### ISSUE TITLE
論文要約いい感じにできる？？

### ISSUE THREAD

**Issue by t-matsumo** [yaaaaashiki/Escapism#283]
#100 

↑マージせずに終わったやつww

**Comment by yaaaaashiki** [comment]
開発者をみつけなきゃ....

**Comment by t-matsumo** [comment]
https://radimrehurek.com/gensim/index.html

↑コレのsummarize関数に分かち書きしたテキスト突っ込めばいいんじゃねとか思ってるwww(実験中...)

**Comment by t-matsumo** [comment]
プルリクだしたよ～

**Comment by yaaaaashiki** [comment]
了解！確認します！

**Comment by yaaaaashiki** [comment]
merged!
