### ISSUE TITLE
論文の詳細画面で研究室ごとの論文検索をするとき期待通り動かない...？

### ISSUE THREAD

**Issue by yaaaaashiki** [yaaaaashiki/Escapism#286]
論文詳細画面から研究室ごとの論文検索のラジオボタンを押すと、
研究室ごとの論文検索は行われず、類似論文がサジェストされる....

**Comment by t-matsumo** [comment]
仕様です...

**Comment by yaaaaashiki** [comment]
類似論文のページはページ遷移で見れる方が使いやすいんじゃないかなーって思った〜
