### ISSUE TITLE
admin 側のページ遷移がイケてない...

### ISSUE THREAD

**Issue by yaaaaashiki** [yaaaaashiki/Escapism#299]
admin ログアウト状態。admin ページにアドレスバーへの URI 入力で遷移するとき、
ユーザ情報入力を求められ、入力後 admin トップページに遷移する。

ユーザ情報入力後は、入力した URI 先に遷移してほしい...

**Comment by t-matsumo** [comment]
↑これ認証方法がイケてないだけじゃんwww

**Comment by yaaaaashiki** [comment]
merged
